### ISSUE TITLE
功能失效

### ISSUE THREAD

**Issue by lf6545** [dofy/utools-ghost-note#1]
现在utools3.0了，现在点击ghost后不能直接打开当前应用绑定的笔记，而是打开了笔记管理界面，能否修复一下呢?

**Comment by dofy** [comment]
有人反馈了这个问题，现在 uTools API 不支持任意窗口匹配了，我找到了一个折衷方案，近期应该能上新版本。

**Comment by lf6545** [comment]
也是我反馈的，我一路找过来的，嘿嘿

**Comment by dofy** [comment]
啊 哈哈哈哈哈哈哈 感谢对这个小插件的支持 🙏

**Comment by dofy** [comment]
> 也是我反馈的，我一路找过来的，嘿嘿

新版已经提交审核了，版本号 v0.2.2
